- name: install tomcat 10
  become: yes
  hosts: appservers
  vars:
    username: tomcat
    groupname: tomcat
    homedir: /opt/tomcat
    shell: /bin/false
    java_version: 11
    MAJOR_VERSION: 10
    VERSION: 10.1.14
  tasks:
    - name: install jdk
      ansible.builtin.apt:
        name: "openjdk-{{ java_version }}-jdk"
        update_cache: yes
        state: present
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        home: "{{ homedir }}"
        create_home: true
        shell: "{{ shell }}"
    - name: Adding Debug statements
      ansible.builtin.debug:
        msg:
        - System has java-version {{ java_version }}
        - System has username as {{ username }}
        - System has groupname as {{ groupname }}
    - name: Download tomcat 10
      ansible.builtin.get_url:
          url: "https://dlcdn.apache.org/tomcat/tomcat-{{ MAJOR_VERSION }}/v{{ VERSION }}/bin/apache-tomcat-{{ VERSION }}.tar.gz"
          dest: /tmp
    - name: Execute the shell command 
      ansible.builtin.shell: "sudo tar -xf /tmp/apache-tomcat-{{ VERSION }}.tar.gz -C /opt/tomcat/"
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "/tmp/apache-tomcat-{{ VERSION }}.tar.gz"
        dest: /opt/tomcat/latest
        owner: tomcat
        group: tomcat
        state: link
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: '0644'
      
