- name: install tomcat 10 on Redhat 9
  become: yes
  hosts: appservers
  vars:
    username: tomcat
    groupname: tomcat
    homedir: /opt/tomcat
    shell: /bin/false
  tasks:
    - name: install jdk
      ansible.builtin.dnf:
        name: "java-{{ java_version }}-openjdk-devel"
        update_cache: yes
        state: present
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        home: "{{ homedir }}"
        create_home: true
        shell: "{{ shell }}"
    - name: Adding Debug statements
      ansible.builtin.debug:
        msg:
        - System has java-version {{ java_version }}
        - System has username as {{ username }}
        - System has groupname as {{ groupname }}
    - name: Install wget package (RedHat based)
      action: yum name='wget' state=installed
    - name: Download tomcat 10
      ansible.builtin.get_url:
          url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ version_tomcat }}/bin/apache-tomcat-{{ version_tomcat }}.tar.gz"
          dest: /tmp
    - name: Execute the shell command 
      ansible.builtin.shell: "sudo tar -xf /tmp/apache-tomcat-{{ version_tomcat }}.tar.gz -C /usr/share/"
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "/usr/share/apache-tomcat-{{ version_tomcat }}"
        dest: /usr/share/tomcat
        owner: tomcat
        group: tomcat
        state: link
    - name: Change file ownership, group and permissions
      ansible.builtin.command: sudo chown -R tomcat:tomcat /usr/share/tomcat
      ansible.builtin.command: sudo chown -R tomcat:tomcat /usr/share/apache-tomcat-9.0.64
    - name: user execute permissions 
      ansible.builtin.command: sudo chmod -R /usr/share/apache-tomcat-9.0.64
    - name: service file
      ansible.builtin.template:
        src: template/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
    - name: daemon reload
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Start service tomcat
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: yes
    - name: check the status 
      ansible.builtin.command: systemctl status tomcat
      register: myoutput
    - name: debug
      ansible.builtin.debug:
        var: myoutput.stdout_lines
    

      